import { useContext } from "react";
import { Container, Row, Col, Button } from "react-bootstrap";
import { ThemeContext } from "../Context/ThemeContext";
import { useNavigate } from "react-router-dom";
// Defining the About component
const About = () => {
  // Context for managing color theme
  const { themeProps } = useContext(ThemeContext);
  const navigate = useNavigate();
  return (
    //Random text generated by ChatGPT
    <div className={themeProps.FooterBarMain} style={{ height: "100vh" }}>
      <Container className={`${themeProps.ModalText} ${themeProps.ModalBG} `}>
        <Row className="text-center">
          <Col>
            <h2>About Us</h2>
            <p>Welcome to TC-Cards!</p>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col>
            <p>
              At TC-Cards, we believe that a first impression can make all the
              difference. That's why it's our mission to provide you with an
              easy and efficient way to create stunning business cards that will
              leave a lasting impact.
            </p>
          </Col>
        </Row>
        <Row className="text-center mb-4">
          <Col>
            <h4>Our Vision</h4>
            <p>
              Our vision is to empower professionals, entrepreneurs, and
              creatives with the tools they need to showcase their unique
              identity and brand. We understand that your business card is more
              than just contact information - it's a representation of you and
              your business. With TC-Cards, you will have the power to design a
              card that speaks volumes about your professionalism and
              creativity.
            </p>
          </Col>
        </Row>
        <Row>
          <Col>
            <h4>What Sets Us Apart</h4>
            <ul>
              <li>
                <strong>Intuitive Design Tools:</strong> We are developing an
                intuitive and user-friendly platform that will allow you to
                effortlessly design a business card that reflects your style and
                personality.
              </li>
              <li>
                <strong>Customization Options:</strong> Choose from a wide range
                of templates and access an extensive library of fonts and color
                palettes, giving you the freedom to create a card that is
                uniquely yours.
              </li>
              <li>
                <strong>Seamless Sharing:</strong> Once you've crafted the
                perfect business card, you will be able to easily share it with
                colleagues, clients, and contacts through various digital
                platforms or print it for face-to-face interactions.
              </li>
              <li>
                <strong>Print and Digital Options:</strong> Whether you prefer a
                physical card or a digital version, we'll have you covered.
                Choose from our high-quality printing options or go green with a
                digital card that can be easily shared via email or social
                media.
              </li>
            </ul>
          </Col>
        </Row>
        <Row>
          <Col>
            <h4>Our Commitment to Excellence</h4>
            <p>
              We are dedicated to providing you with a seamless experience, from
              the moment you start designing your business card to the moment
              it's in your hands. Our team is constantly working behind the
              scenes to ensure that you will have access to the latest design
              trends, features, and technologies.
            </p>
          </Col>
        </Row>
        <Row className="text-center mt-4">
          <Col>
            <h5>Get Ready for the Future</h5>
            <p>
              Experience the future of networking with TC-Cards. Create your
              personalized business card and be prepared to leave a lasting
              impression on every connection you make.
            </p>
            <Button
              variant={themeProps.ModalButtons}
              onClick={() => navigate("/")}
            >
              Get Started
            </Button>
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export { About };
